CREATE TABLE [dbo].[Patrimonio]
(
    [ID] INT NOT NULL IDENTITY(1 ,1),
    [Nome] NVARCHAR(1024) NOT NULL,
    [MarcaID] INT NOT NULL ,
    [Descricao] NVARCHAR(1024),
    [NumeroDoTombo] INT NOT NULL DEFAULT((0)),
 CONSTRAINT [PK_Patrimonio] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
